###
PUT http://localhost:8080/medicos
Content-Type: application/json

{
  "id": 3,
  "endereco": {
    "logradouro": "AAAA",
    "bairro": "AAAA",
    "cep": "999999",
    "cidade": "AAAA",
    "uf": "AA",
    "numero": "999",
    "complemento": "AAA"
  }
}

###
DELETE http://localhost:8080/medicos/3
Accept: application/json

###
GET http://localhost:8080/medicos/10
Accept: application/json

###
GET http://localhost:8080/medicos/algunsdados
Accept: application/json

###
GET http://localhost:8080/medicos/algunsdados?size=2&page=1
Accept: application/json

###
GET http://localhost:8080/medicos/algunsdados?sort=nome
Accept: application/json

###
POST http://localhost:8080/medicos
Content-Type: application/json
Accept: application/json

{
  "nome": "Dilermando Reis",
  "email": "dil@gmail.com",
  "crm": "667777",
  "especialidade": "ORTOPEDIA",
  "telefone": "16992225599",
  "endereco": {
    "logradouro": "RUA DIL",
    "bairro": "BAIRRO DIL",
    "cep": "12345678",
    "cidade": "São Carlos",
    "uf": "SP",
    "numero": "555",
    "complemento": "DILDILDIL"
  }
}

###
POST http://localhost:8080/medicos
Content-Type: application/json
Accept: application/json

{
  "nome": "Asdrubal Zoroastro",
  "email": "asd@gmail.com",
  "crm": "777777",
  "telefone": "17992483333",
  "especialidade": "DERMATOLOGIA",
  "endereco": {
    "logradouro": "Rua Danilo Micalli 50",
    "bairro": "Sao Carlos 3",
    "cep": "13563264",
    "cidade": "São Carlos",
    "uf": "SP",
    "numero": "999",
    "complemento": "casa 74"
  }
}

###
POST http://localhost:8080/medicos
Content-Type: application/json
Accept: application/json

{
  "nome": "Anita Garibaldi",
  "email": "ag@gmail.com",
  "telefone": "16992484444",
  "crm": "444444",
  "especialidade": "ORTOPEDIA",
  "endereco": {
    "logradouro": "RUA QUATRO",
    "bairro": "BAIRRO QUATRO",
    "cep": "44444444",
    "cidade": "Limeira",
    "uf": "SP"
  }
}
